apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: eikr4f4sc-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/eikr4f4sc-java-quarkus-gitops